language: node_js
env: IN_TRAVIS=true
node_js:
- '0.10'

branches:
  only:
    - master
before_install:

install: npm install

before_script:
  - grunt jshint:all
  - grunt run:jasmine
  - JASMINE_CONFIG_PATH=./jasmine.json
  - export JASMINE_CONFIG_PATH

notifications:
  email:
    recipients:
    - cdnadmin@collaborare.net
    on_success: never
    on_failure: always